version: '3'

services:
  app:
    build: .
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 2048M

  db:
    build: ./.docker/mysql
    restart: always
    tty: true
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=school_api
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 2048M
